-- MySQL Script generated by MySQL Workbench
-- 05/13/20 08:36:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBMolino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBMolino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBMolino` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DBMolino` ;

-- -----------------------------------------------------
-- Table `DBMolino`.`Conductor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Conductor` (
  `IdConductor` INT NOT NULL AUTO_INCREMENT,
  `CodConduc` VARCHAR(45) NULL,
  `DNI` INT NULL,
  `Licencia` VARCHAR(15) NULL,
  `Nombre` VARCHAR(60) NULL,
  `Apellidos` VARCHAR(60) NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  `TipoBrevete` VARCHAR(45) NULL,
  `Condicion` VARCHAR(45) NULL,
  `Estado` TINYINT NULL,
  `Observacion` VARCHAR(180) NULL,
  PRIMARY KEY (`IdConductor`),
  UNIQUE INDEX `NumDoc_UNIQUE` (`Licencia` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`EmpreTrans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`EmpreTrans` (
  `IdEmpreTrans` INT NOT NULL AUTO_INCREMENT,
  `Ruc` BIGINT NOT NULL,
  `RazonSocial` VARCHAR(80) NOT NULL,
  `Domicilio` VARCHAR(130) NULL,
  `Correo` VARCHAR(45) NULL,
  `NumCel` VARCHAR(15) NULL,
  `Condicion` VARCHAR(45) NULL,
  `Estado` TINYINT NULL,
  `Observ` VARCHAR(180) NULL,
  PRIMARY KEY (`IdEmpreTrans`),
  UNIQUE INDEX `Ruc_UNIQUE` (`Ruc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Vehiculo` (
  `IdPlaca` INT NOT NULL AUTO_INCREMENT,
  `Placa` VARCHAR(8) NOT NULL,
  `Marca` VARCHAR(45) NULL,
  `Compartimientos` TINYINT NULL,
  `IdEmpreTrans` INT NOT NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdPlaca`),
  UNIQUE INDEX `Placa_UNIQUE` (`Placa` ASC),
  INDEX `fk_Vehiculo_EmpreTrans1_idx` (`IdEmpreTrans` ASC),
  CONSTRAINT `fk_Vehiculo_EmpreTrans1`
    FOREIGN KEY (`IdEmpreTrans`)
    REFERENCES `DBMolino`.`EmpreTrans` (`IdEmpreTrans`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`ConductorVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`ConductorVehiculo` (
  `IdConductorVehiculo` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NULL,
  `IdPlaca` INT NOT NULL,
  `IdConductor` INT NOT NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdConductorVehiculo`),
  INDEX `fk_ConductorVehiculo_Conductor1_idx` (`IdConductor` ASC),
  INDEX `fk_ConductorVehiculo_Vehiculo1_idx` (`IdPlaca` ASC),
  CONSTRAINT `fk_ConductorVehiculo_Conductor1`
    FOREIGN KEY (`IdConductor`)
    REFERENCES `DBMolino`.`Conductor` (`IdConductor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConductorVehiculo_Vehiculo1`
    FOREIGN KEY (`IdPlaca`)
    REFERENCES `DBMolino`.`Vehiculo` (`IdPlaca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`ProveClien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`ProveClien` (
  `IdProveClien` INT NOT NULL AUTO_INCREMENT,
  `RazonSocial` VARCHAR(45) NULL,
  `Ruc` BIGINT NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdProveClien`),
  UNIQUE INDEX `Ruc_UNIQUE` (`Ruc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Empleado` (
  `IdEmpleado` INT NOT NULL AUTO_INCREMENT,
  `DNI` INT NOT NULL,
  `Codigo` VARCHAR(15) NOT NULL,
  `NombreE` VARCHAR(70) NULL,
  `ApellidosE` VARCHAR(70) NULL,
  `Telefono` VARCHAR(12) NULL,
  `Celular` VARCHAR(12) NULL,
  `FechaIngreso` DATE NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdEmpleado`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NULL,
  `Contrasena` VARCHAR(45) NULL,
  `TipoUsuario` VARCHAR(45) NULL,
  `IdEmpleado` INT NOT NULL,
  `Estado` TINYINT NULL,
  `Sector` VARCHAR(60) NOT NULL,
  `Area` VARCHAR(60) NULL,
  PRIMARY KEY (`IdUsuario`),
  INDEX `fk_Usuario_Empleado1_idx` (`IdEmpleado` ASC),
  CONSTRAINT `fk_Usuario_Empleado1`
    FOREIGN KEY (`IdEmpleado`)
    REFERENCES `DBMolino`.`Empleado` (`IdEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`TipoDestino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`TipoDestino` (
  `IdTipoDestino` INT NOT NULL AUTO_INCREMENT,
  `TipoDestino` VARCHAR(50) NOT NULL,
  `CodDestino` VARCHAR(15) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdTipoDestino`),
  UNIQUE INDEX `CodDestino_UNIQUE` (`CodDestino` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Destino` (
  `IdDestino` INT NOT NULL AUTO_INCREMENT,
  `Destino` VARCHAR(80) NOT NULL,
  `CodDestino` VARCHAR(15) NULL,
  `Estado` TINYINT NULL,
  `IdTipoDestino` INT NOT NULL,
  PRIMARY KEY (`IdDestino`),
  UNIQUE INDEX `CodDestino_UNIQUE` (`CodDestino` ASC),
  INDEX `fk_Destino_TipoDestino1_idx` (`IdTipoDestino` ASC),
  CONSTRAINT `fk_Destino_TipoDestino1`
    FOREIGN KEY (`IdTipoDestino`)
    REFERENCES `DBMolino`.`TipoDestino` (`IdTipoDestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`DestinoDesc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`DestinoDesc` (
  `IdDestinoDesc` INT NOT NULL AUTO_INCREMENT,
  `DestinoDes` VARCHAR(80) NOT NULL,
  `CodDestinoDesc` VARCHAR(15) NULL,
  `Estado` TINYINT NOT NULL,
  `IdDestino` INT NOT NULL,
  PRIMARY KEY (`IdDestinoDesc`),
  UNIQUE INDEX `CodDestinoDesc_UNIQUE` (`CodDestinoDesc` ASC),
  INDEX `fk_DestinoDesc_Destino1_idx` (`IdDestino` ASC),
  CONSTRAINT `fk_DestinoDesc_Destino1`
    FOREIGN KEY (`IdDestino`)
    REFERENCES `DBMolino`.`Destino` (`IdDestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`DestinoBloq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`DestinoBloq` (
  `IdDestinoBloq` INT NOT NULL AUTO_INCREMENT,
  `DestinoBloq` VARCHAR(45) NOT NULL,
  `CodDestinoBloq` VARCHAR(15) NULL,
  `Estado` TINYINT NOT NULL,
  `IdDestinoDesc` INT NOT NULL,
  PRIMARY KEY (`IdDestinoBloq`),
  INDEX `fk_DestinoBloq_DestinoDesc1_idx` (`IdDestinoDesc` ASC),
  CONSTRAINT `fk_DestinoBloq_DestinoDesc1`
    FOREIGN KEY (`IdDestinoDesc`)
    REFERENCES `DBMolino`.`DestinoDesc` (`IdDestinoDesc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`TipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`TipoProducto` (
  `IdTipoProducto` INT NOT NULL AUTO_INCREMENT,
  `TipoProducto` VARCHAR(50) NOT NULL,
  `CodTipoProducto` VARCHAR(15) NULL,
  `Estado` TINYINT NOT NULL,
  PRIMARY KEY (`IdTipoProducto`),
  UNIQUE INDEX `CodTipoProducto_UNIQUE` (`CodTipoProducto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`CategoriaProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`CategoriaProd` (
  `IdCategoriaProd` INT NOT NULL AUTO_INCREMENT,
  `CategoriaProd` VARCHAR(50) NOT NULL,
  `CodCategoria` VARCHAR(15) NULL,
  `Estado` TINYINT NOT NULL,
  `IdTipoProducto` INT NOT NULL,
  PRIMARY KEY (`IdCategoriaProd`),
  UNIQUE INDEX `CodCategoria_UNIQUE` (`CodCategoria` ASC),
  INDEX `fk_CategoriaProd_TipoProducto1_idx` (`IdTipoProducto` ASC),
  CONSTRAINT `fk_CategoriaProd_TipoProducto1`
    FOREIGN KEY (`IdTipoProducto`)
    REFERENCES `DBMolino`.`TipoProducto` (`IdTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Producto` (
  `IdProducto` INT NOT NULL AUTO_INCREMENT,
  `Producto` VARCHAR(60) NOT NULL,
  `CodProducto` VARCHAR(60) NULL,
  `Estado` TINYINT NOT NULL,
  `IdCategoriaProd` INT NOT NULL,
  `NombreGuia` VARCHAR(150) NULL,
  PRIMARY KEY (`IdProducto`),
  UNIQUE INDEX `CodProducto_UNIQUE` (`CodProducto` ASC),
  INDEX `fk_Producto_CategoriaProd1_idx` (`IdCategoriaProd` ASC),
  CONSTRAINT `fk_Producto_CategoriaProd1`
    FOREIGN KEY (`IdCategoriaProd`)
    REFERENCES `DBMolino`.`CategoriaProd` (`IdCategoriaProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`DescProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`DescProd` (
  `IdDescProd` INT NOT NULL AUTO_INCREMENT,
  `DescProd` VARCHAR(60) NOT NULL,
  `CodDescProd` VARCHAR(60) NULL,
  `Estado` TINYINT NOT NULL,
  `IdProducto` INT NOT NULL,
  PRIMARY KEY (`IdDescProd`),
  UNIQUE INDEX `CodDescProd_UNIQUE` (`CodDescProd` ASC),
  INDEX `fk_DescProd_Producto1_idx` (`IdProducto` ASC),
  CONSTRAINT `fk_DescProd_Producto1`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `DBMolino`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Peso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Peso` (
  `IdPeso` INT NOT NULL AUTO_INCREMENT,
  `TipoMovimiento` VARCHAR(45) NULL,
  `NumGuia` INT NULL,
  `FechaHoraSal` DATETIME NULL,
  `FechaHoraEnt` DATETIME NULL,
  `PesoCE` INT NULL,
  `PesoCS` INT NULL,
  `NetoC` INT NULL,
  `ObservE` VARCHAR(100) NULL,
  `ObservS` VARCHAR(100) NULL,
  `Estado` VARCHAR(45) NULL,
  `IdUsuario` INT NOT NULL,
  `IdProveClien` INT NOT NULL,
  `Precinto` INT NULL,
  `IdConductorVehiculo` INT NOT NULL,
  `IdDestinoBloq` INT NOT NULL,
  `IdDescProd` INT NOT NULL,
  `NumSemana` INT NULL,
  PRIMARY KEY (`IdPeso`),
  INDEX `fk_Peso_Usuario1_idx` (`IdUsuario` ASC),
  INDEX `fk_Peso_ProveClien1_idx` (`IdProveClien` ASC),
  INDEX `fk_Peso_ConductorVehiculo1_idx` (`IdConductorVehiculo` ASC),
  INDEX `fk_Peso_DestinoBloq1_idx` (`IdDestinoBloq` ASC),
  INDEX `fk_Peso_DescProd1_idx` (`IdDescProd` ASC),
  CONSTRAINT `fk_Peso_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peso_ProveClien1`
    FOREIGN KEY (`IdProveClien`)
    REFERENCES `DBMolino`.`ProveClien` (`IdProveClien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peso_ConductorVehiculo1`
    FOREIGN KEY (`IdConductorVehiculo`)
    REFERENCES `DBMolino`.`ConductorVehiculo` (`IdConductorVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peso_DestinoBloq1`
    FOREIGN KEY (`IdDestinoBloq`)
    REFERENCES `DBMolino`.`DestinoBloq` (`IdDestinoBloq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peso_DescProd1`
    FOREIGN KEY (`IdDescProd`)
    REFERENCES `DBMolino`.`DescProd` (`IdDescProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Guia` (
  `IdGuia` INT NOT NULL AUTO_INCREMENT,
  `NumGuia` INT NULL,
  `FechaGuia` INT NULL,
  `PesoGE` INT NULL,
  `PesoGS` INT NULL,
  `NetoG` INT NULL,
  `Observ` VARCHAR(100) NULL,
  `IdProveClien` INT NOT NULL,
  PRIMARY KEY (`IdGuia`),
  INDEX `fk_Guia_ProveClien1_idx` (`IdProveClien` ASC),
  CONSTRAINT `fk_Guia_ProveClien1`
    FOREIGN KEY (`IdProveClien`)
    REFERENCES `DBMolino`.`ProveClien` (`IdProveClien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Galpon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Galpon` (
  `IdGalpon` INT NOT NULL AUTO_INCREMENT,
  `Galpon` VARCHAR(45) NOT NULL,
  `CodGalpon` VARCHAR(45) NULL,
  `Estado` TINYINT NOT NULL,
  `IdDestinoBloq` INT NOT NULL,
  PRIMARY KEY (`IdGalpon`),
  INDEX `fk_Galpon_DestinoBloq1_idx` (`IdDestinoBloq` ASC),
  CONSTRAINT `fk_Galpon_DestinoBloq1`
    FOREIGN KEY (`IdDestinoBloq`)
    REFERENCES `DBMolino`.`DestinoBloq` (`IdDestinoBloq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`CabeceraPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`CabeceraPedido` (
  `IdCabeceraPedido` INT NOT NULL AUTO_INCREMENT,
  `IdDestinoDesc` INT NOT NULL,
  `OrdenEnvio` INT NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdCabeceraPedido`),
  INDEX `fk_CabeceraPedido_DestinoDesc1_idx` (`IdDestinoDesc` ASC),
  CONSTRAINT `fk_CabeceraPedido_DestinoDesc1`
    FOREIGN KEY (`IdDestinoDesc`)
    REFERENCES `DBMolino`.`DestinoDesc` (`IdDestinoDesc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`PedidoSemanal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`PedidoSemanal` (
  `IdPedidoSemanal` INT NOT NULL AUTO_INCREMENT,
  `IdCabeceraPedido` INT NOT NULL,
  `IdDescProd` INT NOT NULL,
  `CantidadBatch` INT NULL,
  `CantidadKG` INT NULL,
  `NumSemana` INT NULL,
  `Observacion` VARCHAR(120) NULL,
  `IdUsuario` INT NOT NULL,
  `EstadoPS` TINYINT NULL,
  `Estado` TINYINT NULL,
  `Fecha` DATETIME NULL,
  `IdDestinoBloq` INT NOT NULL,
  PRIMARY KEY (`IdPedidoSemanal`),
  INDEX `fk_PedidoSemanal_DescProd1_idx` (`IdDescProd` ASC),
  INDEX `fk_PedidoSemanal_CabeceraPedido1_idx` (`IdCabeceraPedido` ASC),
  INDEX `fk_PedidoSemanal_Usuario1_idx` (`IdUsuario` ASC),
  INDEX `fk_PedidoSemanal_DestinoBloq1_idx` (`IdDestinoBloq` ASC),
  CONSTRAINT `fk_PedidoSemanal_DescProd1`
    FOREIGN KEY (`IdDescProd`)
    REFERENCES `DBMolino`.`DescProd` (`IdDescProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PedidoSemanal_CabeceraPedido1`
    FOREIGN KEY (`IdCabeceraPedido`)
    REFERENCES `DBMolino`.`CabeceraPedido` (`IdCabeceraPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PedidoSemanal_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PedidoSemanal_DestinoBloq1`
    FOREIGN KEY (`IdDestinoBloq`)
    REFERENCES `DBMolino`.`DestinoBloq` (`IdDestinoBloq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Pedido` (
  `IdPedido` INT NOT NULL AUTO_INCREMENT,
  `CantidadBatch` INT NULL,
  `Observacion` VARCHAR(120) NULL,
  `Fecha` DATETIME NULL,
  `Estado` VARCHAR(45) NULL,
  `CantidadKG` VARCHAR(45) NULL,
  `IdUsuario` INT NOT NULL,
  `NumSemana` INT NULL,
  `EstadoP` INT NULL,
  `IdPedidoSemanal` INT NOT NULL,
  `TipoTransporte` VARCHAR(65) NULL,
  PRIMARY KEY (`IdPedido`),
  INDEX `fk_Pedido_Usuario1_idx` (`IdUsuario` ASC),
  INDEX `fk_Pedido_PedidoSemanal1_idx` (`IdPedidoSemanal` ASC),
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_PedidoSemanal1`
    FOREIGN KEY (`IdPedidoSemanal`)
    REFERENCES `DBMolino`.`PedidoSemanal` (`IdPedidoSemanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Panel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Panel` (
  `IdPanel` INT NOT NULL AUTO_INCREMENT,
  `IdPedido` INT NOT NULL,
  `CodProduccion` INT NULL,
  `NumSilo` VARCHAR(3) NULL,
  `CantidadBatch` INT NULL,
  `PesoPanel` INT NULL,
  `IdUsuario` INT NOT NULL,
  `Estado` TINYINT NULL,
  `NumSemana` INT NULL,
  `Fecha` DATETIME NULL,
  PRIMARY KEY (`IdPanel`),
  UNIQUE INDEX `CodProduccion_UNIQUE` (`CodProduccion` ASC),
  INDEX `fk_Panel_Usuario1_idx` (`IdUsuario` ASC),
  INDEX `fk_Panel_Pedido1_idx` (`IdPedido` ASC),
  CONSTRAINT `fk_Panel_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Panel_Pedido1`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `DBMolino`.`Pedido` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Despacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Despacho` (
  `IdDespacho` INT NOT NULL AUTO_INCREMENT,
  `Destino` VARCHAR(45) NULL,
  `Fecha` DATETIME NULL,
  `Estado` TINYINT NULL,
  `IdPanel` INT NOT NULL,
  `IdUsuario` INT NOT NULL,
  `NumSemana` INT NULL,
  PRIMARY KEY (`IdDespacho`),
  INDEX `fk_Despacho_Panel1_idx` (`IdPanel` ASC),
  INDEX `fk_Despacho_Usuario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_Despacho_Panel1`
    FOREIGN KEY (`IdPanel`)
    REFERENCES `DBMolino`.`Panel` (`IdPanel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Despacho_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`DetalleDespacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`DetalleDespacho` (
  `IdDetalleDespacho` INT NOT NULL AUTO_INCREMENT,
  `IdDespacho` INT NOT NULL,
  `IdPeso` INT NOT NULL,
  `IdGalpon` INT NOT NULL,
  `IdDescProd` INT NOT NULL,
  PRIMARY KEY (`IdDetalleDespacho`),
  INDEX `fk_DetalleDespacho_Despacho1_idx` (`IdDespacho` ASC),
  INDEX `fk_DetalleDespacho_Peso1_idx` (`IdPeso` ASC),
  INDEX `fk_DetalleDespacho_Galpon1_idx` (`IdGalpon` ASC),
  INDEX `fk_DetalleDespacho_DescProd1_idx` (`IdDescProd` ASC),
  CONSTRAINT `fk_DetalleDespacho_Despacho1`
    FOREIGN KEY (`IdDespacho`)
    REFERENCES `DBMolino`.`Despacho` (`IdDespacho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleDespacho_Peso1`
    FOREIGN KEY (`IdPeso`)
    REFERENCES `DBMolino`.`Peso` (`IdPeso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleDespacho_Galpon1`
    FOREIGN KEY (`IdGalpon`)
    REFERENCES `DBMolino`.`Galpon` (`IdGalpon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleDespacho_DescProd1`
    FOREIGN KEY (`IdDescProd`)
    REFERENCES `DBMolino`.`DescProd` (`IdDescProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`GuiaCalera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`GuiaCalera` (
  `IdGuiaCalera` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdGuiaCalera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Permiso` (
  `IdPermiso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdPermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`UsuarioPermiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`UsuarioPermiso` (
  `idUsuarioPermiso` INT NOT NULL AUTO_INCREMENT,
  `IdUsuario` INT NOT NULL,
  `IdPermiso` INT NOT NULL,
  PRIMARY KEY (`idUsuarioPermiso`),
  INDEX `fk_UsuarioPermiso_Usuario1_idx` (`IdUsuario` ASC),
  INDEX `fk_UsuarioPermiso_Permiso1_idx` (`IdPermiso` ASC),
  CONSTRAINT `fk_UsuarioPermiso_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioPermiso_Permiso1`
    FOREIGN KEY (`IdPermiso`)
    REFERENCES `DBMolino`.`Permiso` (`IdPermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`EntradaySalidaVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`EntradaySalidaVehiculo` (
  `IdEntradaySalidaVehiculo` INT NOT NULL AUTO_INCREMENT,
  `EstadoVehi` TINYINT NULL,
  `FechaMov` DATETIME NULL,
  `IdConductorVehiculo` INT NOT NULL,
  `EstadoRegistro` TINYINT NULL,
  `IdUsuario` INT NOT NULL,
  PRIMARY KEY (`IdEntradaySalidaVehiculo`),
  INDEX `fk_EntradaySalidaVehiculo_ConductorVehiculo1_idx` (`IdConductorVehiculo` ASC),
  INDEX `fk_EntradaySalidaVehiculo_Usuario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_EntradaySalidaVehiculo_ConductorVehiculo1`
    FOREIGN KEY (`IdConductorVehiculo`)
    REFERENCES `DBMolino`.`ConductorVehiculo` (`IdConductorVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EntradaySalidaVehiculo_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`EstadoPlanta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`EstadoPlanta` (
  `IdEstadoPlanta` INT NOT NULL AUTO_INCREMENT,
  `EstadoPlanta` VARCHAR(45) NULL,
  `Tema` VARCHAR(60) NULL,
  `Detalle` VARCHAR(120) NULL,
  `HoraInicio` DATETIME NULL,
  `HoraFin` DATETIME NULL,
  `EstadoP` TINYINT NULL,
  `Estado` TINYINT NULL,
  `IdUsuario` INT NOT NULL,
  `NumSemana` INT NULL,
  PRIMARY KEY (`IdEstadoPlanta`),
  INDEX `fk_EstadoPlanta_Usuario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_EstadoPlanta_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Precio` (
  `IdPrecio` INT NOT NULL AUTO_INCREMENT,
  `Precio` DECIMAL(7,2) NULL,
  `NumSemana` INT NULL,
  `IdDescProd` INT NOT NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdPrecio`),
  INDEX `fk_Precio_DescProd1_idx` (`IdDescProd` ASC),
  CONSTRAINT `fk_Precio_DescProd1`
    FOREIGN KEY (`IdDescProd`)
    REFERENCES `DBMolino`.`DescProd` (`IdDescProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Variaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Variaciones` (
  `IdVariaciones` INT NOT NULL AUTO_INCREMENT,
  `IdPedidoSemanal` INT NOT NULL,
  `CantidadBatch` INT NULL,
  `Motivo` VARCHAR(65) NULL,
  `Detalle` VARCHAR(120) NULL,
  `IdUsuario` INT NOT NULL,
  `EstadoVA` TINYINT NULL,
  `Estado` TINYINT NULL,
  `Fecha` DATETIME NULL,
  PRIMARY KEY (`IdVariaciones`),
  INDEX `fk_Variaciones_PedidoSemanal1_idx` (`IdPedidoSemanal` ASC),
  INDEX `fk_Variaciones_Usuario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_Variaciones_PedidoSemanal1`
    FOREIGN KEY (`IdPedidoSemanal`)
    REFERENCES `DBMolino`.`PedidoSemanal` (`IdPedidoSemanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Variaciones_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`DescProdEmpaque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`DescProdEmpaque` (
  `IdDescProdEmpaque` INT NOT NULL AUTO_INCREMENT,
  `IdDescProd` INT NOT NULL,
  `Presentacion` VARCHAR(65) NULL,
  `Paquete` DECIMAL(7,2) NULL,
  `Unidad` DECIMAL(7,2) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdDescProdEmpaque`),
  INDEX `fk_DescProdEmpaque_DescProd1_idx` (`IdDescProd` ASC),
  CONSTRAINT `fk_DescProdEmpaque_DescProd1`
    FOREIGN KEY (`IdDescProd`)
    REFERENCES `DBMolino`.`DescProd` (`IdDescProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`AlmacenEntrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`AlmacenEntrada` (
  `IdAlmacenEntrada` INT NOT NULL AUTO_INCREMENT,
  `IdDescProdEmpaque` INT NOT NULL,
  `Lote` VARCHAR(65) NULL,
  `Cantidad` DECIMAL(7,2) NULL,
  `Fecha` DATETIME NULL,
  `Placa` VARCHAR(9) NULL,
  `EstadoL` TINYINT NULL,
  `Estado` TINYINT NULL,
  `IdUsuario` INT NOT NULL,
  PRIMARY KEY (`IdAlmacenEntrada`),
  INDEX `fk_Almacen_DescProdEmpaque1_idx` (`IdDescProdEmpaque` ASC),
  UNIQUE INDEX `Lote_UNIQUE` (`Lote` ASC),
  INDEX `fk_AlmacenEntrada_Usuario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_Almacen_DescProdEmpaque1`
    FOREIGN KEY (`IdDescProdEmpaque`)
    REFERENCES `DBMolino`.`DescProdEmpaque` (`IdDescProdEmpaque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlmacenEntrada_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Traslado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Traslado` (
  `IdTraslado` INT NOT NULL AUTO_INCREMENT,
  `IdAlmacenEntrada` INT NOT NULL,
  `Cantidad` INT NULL,
  `Estado` TINYINT NULL,
  `IdUsuario` INT NOT NULL,
  `Area` VARCHAR(45) NULL,
  `Fecha` DATETIME NULL,
  `EstadoP` TINYINT NULL,
  `FechaP` DATETIME NULL,
  PRIMARY KEY (`IdTraslado`),
  INDEX `fk_SalidaAlmacen_Almacen1_idx` (`IdAlmacenEntrada` ASC),
  INDEX `fk_SalidaAlmacen_Usuario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_SalidaAlmacen_Almacen1`
    FOREIGN KEY (`IdAlmacenEntrada`)
    REFERENCES `DBMolino`.`AlmacenEntrada` (`IdAlmacenEntrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SalidaAlmacen_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
