-- MySQL Script generated by MySQL Workbench
-- 03/04/20 10:26:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBMolino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBMolino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBMolino` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DBMolino` ;

-- -----------------------------------------------------
-- Table `DBMolino`.`Conductor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Conductor` (
  `IdConductor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `CodConduc` VARCHAR(45) NULL COMMENT '',
  `DNI` INT NULL COMMENT '',
  `Licencia` VARCHAR(15) NULL COMMENT '',
  `Nombre` VARCHAR(60) NULL COMMENT '',
  `Apellidos` VARCHAR(60) NULL COMMENT '',
  `Nacionalidad` VARCHAR(45) NULL COMMENT '',
  `TipoBrevete` VARCHAR(45) NULL COMMENT '',
  `Condicion` VARCHAR(45) NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  `Observacion` VARCHAR(180) NULL COMMENT '',
  PRIMARY KEY (`IdConductor`)  COMMENT '',
  UNIQUE INDEX `NumDoc_UNIQUE` (`Licencia` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`EmpreTrans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`EmpreTrans` (
  `IdEmpreTrans` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Ruc` BIGINT NOT NULL COMMENT '',
  `RazonSocial` VARCHAR(80) NOT NULL COMMENT '',
  `Domicilio` VARCHAR(130) NULL COMMENT '',
  `Correo` VARCHAR(45) NULL COMMENT '',
  `NumCel` VARCHAR(15) NULL COMMENT '',
  `Condicion` VARCHAR(45) NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  `Observ` VARCHAR(180) NULL COMMENT '',
  PRIMARY KEY (`IdEmpreTrans`)  COMMENT '',
  UNIQUE INDEX `Ruc_UNIQUE` (`Ruc` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Vehiculo` (
  `IdPlaca` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Placa` VARCHAR(8) NOT NULL COMMENT '',
  `Marca` VARCHAR(45) NULL COMMENT '',
  `Compartimientos` TINYINT NULL COMMENT '',
  `IdEmpreTrans` INT NOT NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  PRIMARY KEY (`IdPlaca`)  COMMENT '',
  UNIQUE INDEX `Placa_UNIQUE` (`Placa` ASC)  COMMENT '',
  INDEX `fk_Vehiculo_EmpreTrans1_idx` (`IdEmpreTrans` ASC)  COMMENT '',
  CONSTRAINT `fk_Vehiculo_EmpreTrans1`
    FOREIGN KEY (`IdEmpreTrans`)
    REFERENCES `DBMolino`.`EmpreTrans` (`IdEmpreTrans`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`ConductorVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`ConductorVehiculo` (
  `IdConductorVehiculo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha` DATETIME NULL COMMENT '',
  `IdPlaca` INT NOT NULL COMMENT '',
  `IdConductor` INT NOT NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  PRIMARY KEY (`IdConductorVehiculo`)  COMMENT '',
  INDEX `fk_ConductorVehiculo_Conductor1_idx` (`IdConductor` ASC)  COMMENT '',
  INDEX `fk_ConductorVehiculo_Vehiculo1_idx` (`IdPlaca` ASC)  COMMENT '',
  CONSTRAINT `fk_ConductorVehiculo_Conductor1`
    FOREIGN KEY (`IdConductor`)
    REFERENCES `DBMolino`.`Conductor` (`IdConductor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConductorVehiculo_Vehiculo1`
    FOREIGN KEY (`IdPlaca`)
    REFERENCES `DBMolino`.`Vehiculo` (`IdPlaca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`ProveClien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`ProveClien` (
  `IdProveClien` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `RazonSocial` VARCHAR(45) NULL COMMENT '',
  `Ruc` BIGINT NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  PRIMARY KEY (`IdProveClien`)  COMMENT '',
  UNIQUE INDEX `Ruc_UNIQUE` (`Ruc` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Empleado` (
  `IdEmpleado` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `DNI` INT NOT NULL COMMENT '',
  `Codigo` VARCHAR(15) NOT NULL COMMENT '',
  `NombreE` VARCHAR(70) NULL COMMENT '',
  `ApellidosE` VARCHAR(70) NULL COMMENT '',
  `Telefono` VARCHAR(12) NULL COMMENT '',
  `Celular` VARCHAR(12) NULL COMMENT '',
  `FechaIngreso` DATE NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  PRIMARY KEY (`IdEmpleado`)  COMMENT '',
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC)  COMMENT '',
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Usuario` VARCHAR(45) NULL COMMENT '',
  `Contrasena` VARCHAR(45) NULL COMMENT '',
  `TipoUsuario` VARCHAR(45) NULL COMMENT '',
  `IdEmpleado` INT NOT NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  `Sector` VARCHAR(60) NOT NULL COMMENT '',
  PRIMARY KEY (`IdUsuario`)  COMMENT '',
  INDEX `fk_Usuario_Empleado1_idx` (`IdEmpleado` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_Empleado1`
    FOREIGN KEY (`IdEmpleado`)
    REFERENCES `DBMolino`.`Empleado` (`IdEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`TipoDestino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`TipoDestino` (
  `IdTipoDestino` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `TipoDestino` VARCHAR(50) NOT NULL COMMENT '',
  `CodDestino` VARCHAR(15) NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  PRIMARY KEY (`IdTipoDestino`)  COMMENT '',
  UNIQUE INDEX `CodDestino_UNIQUE` (`CodDestino` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Destino` (
  `IdDestino` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Destino` VARCHAR(80) NOT NULL COMMENT '',
  `CodDestino` VARCHAR(15) NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  `IdTipoDestino` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdDestino`)  COMMENT '',
  UNIQUE INDEX `CodDestino_UNIQUE` (`CodDestino` ASC)  COMMENT '',
  INDEX `fk_Destino_TipoDestino1_idx` (`IdTipoDestino` ASC)  COMMENT '',
  CONSTRAINT `fk_Destino_TipoDestino1`
    FOREIGN KEY (`IdTipoDestino`)
    REFERENCES `DBMolino`.`TipoDestino` (`IdTipoDestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`DestinoDesc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`DestinoDesc` (
  `IdDestinoDesc` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `DestinoDes` VARCHAR(80) NOT NULL COMMENT '',
  `CodDestinoDesc` VARCHAR(15) NULL COMMENT '',
  `Estado` TINYINT NOT NULL COMMENT '',
  `IdDestino` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdDestinoDesc`)  COMMENT '',
  UNIQUE INDEX `CodDestinoDesc_UNIQUE` (`CodDestinoDesc` ASC)  COMMENT '',
  INDEX `fk_DestinoDesc_Destino1_idx` (`IdDestino` ASC)  COMMENT '',
  CONSTRAINT `fk_DestinoDesc_Destino1`
    FOREIGN KEY (`IdDestino`)
    REFERENCES `DBMolino`.`Destino` (`IdDestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`DestinoBloq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`DestinoBloq` (
  `IdDestinoBloq` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `DestinoBloq` VARCHAR(45) NOT NULL COMMENT '',
  `CodDestinoBloq` VARCHAR(15) NULL COMMENT '',
  `Estado` TINYINT NOT NULL COMMENT '',
  `IdDestinoDesc` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdDestinoBloq`)  COMMENT '',
  INDEX `fk_DestinoBloq_DestinoDesc1_idx` (`IdDestinoDesc` ASC)  COMMENT '',
  CONSTRAINT `fk_DestinoBloq_DestinoDesc1`
    FOREIGN KEY (`IdDestinoDesc`)
    REFERENCES `DBMolino`.`DestinoDesc` (`IdDestinoDesc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`TipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`TipoProducto` (
  `IdTipoProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `TipoProducto` VARCHAR(50) NOT NULL COMMENT '',
  `CodTipoProducto` VARCHAR(15) NULL COMMENT '',
  `Estado` TINYINT NOT NULL COMMENT '',
  PRIMARY KEY (`IdTipoProducto`)  COMMENT '',
  UNIQUE INDEX `CodTipoProducto_UNIQUE` (`CodTipoProducto` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`CategoriaProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`CategoriaProd` (
  `IdCategoriaProd` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `CategoriaProd` VARCHAR(50) NOT NULL COMMENT '',
  `CodCategoria` VARCHAR(15) NULL COMMENT '',
  `Estado` TINYINT NOT NULL COMMENT '',
  `IdTipoProducto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdCategoriaProd`)  COMMENT '',
  UNIQUE INDEX `CodCategoria_UNIQUE` (`CodCategoria` ASC)  COMMENT '',
  INDEX `fk_CategoriaProd_TipoProducto1_idx` (`IdTipoProducto` ASC)  COMMENT '',
  CONSTRAINT `fk_CategoriaProd_TipoProducto1`
    FOREIGN KEY (`IdTipoProducto`)
    REFERENCES `DBMolino`.`TipoProducto` (`IdTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Producto` (
  `IdProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Producto` VARCHAR(60) NOT NULL COMMENT '',
  `CodProducto` VARCHAR(60) NULL COMMENT '',
  `Estado` TINYINT NOT NULL COMMENT '',
  `IdCategoriaProd` INT NOT NULL COMMENT '',
  `NombreGuia` VARCHAR(150) NULL COMMENT '',
  PRIMARY KEY (`IdProducto`)  COMMENT '',
  UNIQUE INDEX `CodProducto_UNIQUE` (`CodProducto` ASC)  COMMENT '',
  INDEX `fk_Producto_CategoriaProd1_idx` (`IdCategoriaProd` ASC)  COMMENT '',
  CONSTRAINT `fk_Producto_CategoriaProd1`
    FOREIGN KEY (`IdCategoriaProd`)
    REFERENCES `DBMolino`.`CategoriaProd` (`IdCategoriaProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`DescProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`DescProd` (
  `IdDescProd` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `DescProd` VARCHAR(60) NOT NULL COMMENT '',
  `CodDescProd` VARCHAR(60) NULL COMMENT '',
  `Estado` TINYINT NOT NULL COMMENT '',
  `IdProducto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdDescProd`)  COMMENT '',
  UNIQUE INDEX `CodDescProd_UNIQUE` (`CodDescProd` ASC)  COMMENT '',
  INDEX `fk_DescProd_Producto1_idx` (`IdProducto` ASC)  COMMENT '',
  CONSTRAINT `fk_DescProd_Producto1`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `DBMolino`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Peso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Peso` (
  `IdPeso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `TipoMovimiento` VARCHAR(45) NULL COMMENT '',
  `NumGuia` INT NULL COMMENT '',
  `FechaHoraSal` DATETIME NULL COMMENT '',
  `FechaHoraEnt` DATETIME NULL COMMENT '',
  `PesoCE` INT NULL COMMENT '',
  `PesoCS` INT NULL COMMENT '',
  `NetoC` INT NULL COMMENT '',
  `ObservE` VARCHAR(100) NULL COMMENT '',
  `ObservS` VARCHAR(100) NULL COMMENT '',
  `Estado` VARCHAR(45) NULL COMMENT '',
  `IdUsuario` INT NOT NULL COMMENT '',
  `IdProveClien` INT NOT NULL COMMENT '',
  `Precinto` INT NULL COMMENT '',
  `IdConductorVehiculo` INT NOT NULL COMMENT '',
  `IdDestinoBloq` INT NOT NULL COMMENT '',
  `IdDescProd` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdPeso`)  COMMENT '',
  INDEX `fk_Peso_Usuario1_idx` (`IdUsuario` ASC)  COMMENT '',
  INDEX `fk_Peso_ProveClien1_idx` (`IdProveClien` ASC)  COMMENT '',
  INDEX `fk_Peso_ConductorVehiculo1_idx` (`IdConductorVehiculo` ASC)  COMMENT '',
  INDEX `fk_Peso_DestinoBloq1_idx` (`IdDestinoBloq` ASC)  COMMENT '',
  INDEX `fk_Peso_DescProd1_idx` (`IdDescProd` ASC)  COMMENT '',
  CONSTRAINT `fk_Peso_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peso_ProveClien1`
    FOREIGN KEY (`IdProveClien`)
    REFERENCES `DBMolino`.`ProveClien` (`IdProveClien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peso_ConductorVehiculo1`
    FOREIGN KEY (`IdConductorVehiculo`)
    REFERENCES `DBMolino`.`ConductorVehiculo` (`IdConductorVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peso_DestinoBloq1`
    FOREIGN KEY (`IdDestinoBloq`)
    REFERENCES `DBMolino`.`DestinoBloq` (`IdDestinoBloq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peso_DescProd1`
    FOREIGN KEY (`IdDescProd`)
    REFERENCES `DBMolino`.`DescProd` (`IdDescProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Guia` (
  `IdGuia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NumGuia` INT NULL COMMENT '',
  `FechaGuia` INT NULL COMMENT '',
  `PesoGE` INT NULL COMMENT '',
  `PesoGS` INT NULL COMMENT '',
  `NetoG` INT NULL COMMENT '',
  `Observ` VARCHAR(100) NULL COMMENT '',
  `IdProveClien` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdGuia`)  COMMENT '',
  INDEX `fk_Guia_ProveClien1_idx` (`IdProveClien` ASC)  COMMENT '',
  CONSTRAINT `fk_Guia_ProveClien1`
    FOREIGN KEY (`IdProveClien`)
    REFERENCES `DBMolino`.`ProveClien` (`IdProveClien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Galpon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Galpon` (
  `IdGalpon` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Galpon` VARCHAR(45) NOT NULL COMMENT '',
  `CodGalpon` VARCHAR(45) NULL COMMENT '',
  `Estado` TINYINT NOT NULL COMMENT '',
  `IdDestinoBloq` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdGalpon`)  COMMENT '',
  INDEX `fk_Galpon_DestinoBloq1_idx` (`IdDestinoBloq` ASC)  COMMENT '',
  CONSTRAINT `fk_Galpon_DestinoBloq1`
    FOREIGN KEY (`IdDestinoBloq`)
    REFERENCES `DBMolino`.`DestinoBloq` (`IdDestinoBloq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`CabeceraPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`CabeceraPedido` (
  `IdCabeceraPedido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `IdDestinoDesc` INT NOT NULL COMMENT '',
  `TipoTransporte` VARCHAR(45) NULL COMMENT '',
  `OrdenEnvio` VARCHAR(45) NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  PRIMARY KEY (`IdCabeceraPedido`)  COMMENT '',
  INDEX `fk_CabeceraPedido_DestinoDesc1_idx` (`IdDestinoDesc` ASC)  COMMENT '',
  CONSTRAINT `fk_CabeceraPedido_DestinoDesc1`
    FOREIGN KEY (`IdDestinoDesc`)
    REFERENCES `DBMolino`.`DestinoDesc` (`IdDestinoDesc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Pedido` (
  `IdPedido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `IdCabeceraPedido` INT NOT NULL COMMENT '',
  `CantidadBatch` INT NULL COMMENT '',
  `Observacion` VARCHAR(120) NULL COMMENT '',
  `Fecha` DATETIME NULL COMMENT '',
  `Estado` VARCHAR(45) NULL COMMENT '',
  `CantidadKG` VARCHAR(45) NULL COMMENT '',
  `IdUsuario` INT NOT NULL COMMENT '',
  `IdDescProd` INT NOT NULL COMMENT '',
  `NumSemana` INT NULL COMMENT '',
  `Pedidocol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`IdPedido`)  COMMENT '',
  INDEX `fk_Pedido_CabeceraPedido1_idx` (`IdCabeceraPedido` ASC)  COMMENT '',
  INDEX `fk_Pedido_Usuario1_idx` (`IdUsuario` ASC)  COMMENT '',
  INDEX `fk_Pedido_DescProd1_idx` (`IdDescProd` ASC)  COMMENT '',
  CONSTRAINT `fk_Pedido_CabeceraPedido1`
    FOREIGN KEY (`IdCabeceraPedido`)
    REFERENCES `DBMolino`.`CabeceraPedido` (`IdCabeceraPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_DescProd1`
    FOREIGN KEY (`IdDescProd`)
    REFERENCES `DBMolino`.`DescProd` (`IdDescProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Panel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Panel` (
  `IdPanel` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `IdPedido` INT NOT NULL COMMENT '',
  `CodProduccion` INT NOT NULL COMMENT '',
  `NumSilo` VARCHAR(3) NULL COMMENT '',
  `CantidadBatch` INT NULL COMMENT '',
  `PesoPanel` VARCHAR(45) NULL COMMENT '',
  `IdUsuario` INT NOT NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  `NumSemana` INT NULL COMMENT '',
  PRIMARY KEY (`IdPanel`)  COMMENT '',
  UNIQUE INDEX `CodProduccion_UNIQUE` (`CodProduccion` ASC)  COMMENT '',
  INDEX `fk_Panel_Usuario1_idx` (`IdUsuario` ASC)  COMMENT '',
  INDEX `fk_Panel_Pedido1_idx` (`IdPedido` ASC)  COMMENT '',
  CONSTRAINT `fk_Panel_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Panel_Pedido1`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `DBMolino`.`Pedido` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Despacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Despacho` (
  `IdDespacho` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Destino` VARCHAR(45) NULL COMMENT '',
  `Fecha` DATETIME NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  `IdPanel` INT NOT NULL COMMENT '',
  `IdUsuario` INT NOT NULL COMMENT '',
  `NumSemana` INT NULL COMMENT '',
  PRIMARY KEY (`IdDespacho`)  COMMENT '',
  INDEX `fk_Despacho_Panel1_idx` (`IdPanel` ASC)  COMMENT '',
  INDEX `fk_Despacho_Usuario1_idx` (`IdUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Despacho_Panel1`
    FOREIGN KEY (`IdPanel`)
    REFERENCES `DBMolino`.`Panel` (`IdPanel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Despacho_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`DetalleDespacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`DetalleDespacho` (
  `IdDetalleDespacho` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `IdDespacho` INT NOT NULL COMMENT '',
  `IdPeso` INT NOT NULL COMMENT '',
  `IdGalpon` INT NOT NULL COMMENT '',
  `IdDescProd` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdDetalleDespacho`)  COMMENT '',
  INDEX `fk_DetalleDespacho_Despacho1_idx` (`IdDespacho` ASC)  COMMENT '',
  INDEX `fk_DetalleDespacho_Peso1_idx` (`IdPeso` ASC)  COMMENT '',
  INDEX `fk_DetalleDespacho_Galpon1_idx` (`IdGalpon` ASC)  COMMENT '',
  INDEX `fk_DetalleDespacho_DescProd1_idx` (`IdDescProd` ASC)  COMMENT '',
  CONSTRAINT `fk_DetalleDespacho_Despacho1`
    FOREIGN KEY (`IdDespacho`)
    REFERENCES `DBMolino`.`Despacho` (`IdDespacho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleDespacho_Peso1`
    FOREIGN KEY (`IdPeso`)
    REFERENCES `DBMolino`.`Peso` (`IdPeso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleDespacho_Galpon1`
    FOREIGN KEY (`IdGalpon`)
    REFERENCES `DBMolino`.`Galpon` (`IdGalpon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleDespacho_DescProd1`
    FOREIGN KEY (`IdDescProd`)
    REFERENCES `DBMolino`.`DescProd` (`IdDescProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`GuiaCalera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`GuiaCalera` (
  `IdGuiaCalera` INT NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`IdGuiaCalera`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`Permiso` (
  `IdPermiso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Estado` TINYINT NULL COMMENT '',
  PRIMARY KEY (`IdPermiso`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`UsuarioPermiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`UsuarioPermiso` (
  `idUsuarioPermiso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `IdUsuario` INT NOT NULL COMMENT '',
  `IdPermiso` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idUsuarioPermiso`)  COMMENT '',
  INDEX `fk_UsuarioPermiso_Usuario1_idx` (`IdUsuario` ASC)  COMMENT '',
  INDEX `fk_UsuarioPermiso_Permiso1_idx` (`IdPermiso` ASC)  COMMENT '',
  CONSTRAINT `fk_UsuarioPermiso_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioPermiso_Permiso1`
    FOREIGN KEY (`IdPermiso`)
    REFERENCES `DBMolino`.`Permiso` (`IdPermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMolino`.`EntradaySalidaVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMolino`.`EntradaySalidaVehiculo` (
  `IdEntradaySalidaVehiculo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `EstadoVehi` TINYINT NULL COMMENT '',
  `FechaMov` DATETIME NULL COMMENT '',
  `IdConductorVehiculo` INT NOT NULL COMMENT '',
  `EstadoRegistro` TINYINT NULL COMMENT '',
  `IdUsuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdEntradaySalidaVehiculo`)  COMMENT '',
  INDEX `fk_EntradaySalidaVehiculo_ConductorVehiculo1_idx` (`IdConductorVehiculo` ASC)  COMMENT '',
  INDEX `fk_EntradaySalidaVehiculo_Usuario1_idx` (`IdUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_EntradaySalidaVehiculo_ConductorVehiculo1`
    FOREIGN KEY (`IdConductorVehiculo`)
    REFERENCES `DBMolino`.`ConductorVehiculo` (`IdConductorVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EntradaySalidaVehiculo_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBMolino`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
